### ISSUE TITLE
[Suggestion] Small tweaks

### ISSUE THREAD

**Issue by DevTimur** [Lemonszz/delivery#1]
**FEEL FREE TO USE ANY OR NONE OF THIS TWEAKS, THAT'S ONLY SUGGESTIONS**
--------------------------------------------------------------------------
Slightly remake Crafttweaker apearence
Instead of:
_mods.Delivery.Store.addTrade(<minecraft:apple>, <ore:ingotIron>, <minecraft:obsidian> * 5);_
make 
_mods.Delivery.Store.addTrade(<minecraft:apple>, [<ore:ingotIron>, <minecraft:obsidian> * 5]);_ (add brakets)
That will make trade recipes more obvious for modpack makers.
--------------------------------------------------------------------------
Add randomly apearing trades.
For example every day (can be changed in config) you got random trade:
_mods.Delivery.Store.addTrade(<minecraft:apple>, [<ore:ingotIron>, <minecraft:obsidian> * 5], 99);_
Where 99 is chance of this trade to apear.
--------------------------------------------------------------------------
Add limited trades.
For example every day (can be changed in config) you got random limited trade:
_mods.Delivery.Store.addTrade(<minecraft:apple>, [<ore:ingotIron>, <minecraft:obsidian> * 5], 99, 5);_
Where 99 is chance of this trade to apear, and 5 is number of times you can do this trade.
--------------------------------------------------------------------------
Make green confirm button not close trade window, but blink gray for a moment, and if you press it again, you make another trade. Maybe make so all traded items comes in single box.
--------------------------------------------------------------------------
Make so you don't break crate, but open it as a box, and take items. You can't put items inside, only take. When you take last item, crate disapear (break itself).
--------------------------------------------------------------------------
Add custom sound of box incoming. Like... Jetplane sound, meteor sound, portal sound etc. I think it would be best to allow modpack maker to use own sounds. Maybe also add effect of delivery, like flames for meteor
--------------------------------------------------------------------------
A may be cool if you can also select model of crate. Meteor, sci fi drop pod, wooden crate, metal crate, magical box, etc.
--------------------------------------------------------------------------
**SOME OF THIS TWEAKS MOSTLY DECORATIVE, IF YOU DON'T WANT YOU CAN USE NONE OF THEM**

**Comment by Lemonszz** [comment]
Thanks for the suggestions, I'll put them on my to do list! 

It's actually already possible to use an array as the arguments
`mods.Delivery.Store.addTrade(<minecraft:apple>, [<ore:plankWood>, <ore:ingotIron>, <minecraft:obsidian> * 5]);`
is just as valid as
`mods.Delivery.Store.addTrade(<minecraft:apple>, <ore:plankWood>, <ore:ingotIron>, <minecraft:obsidian> * 5);`

It's possible to disable the GUI closing in the config, I do like the idea of disabling the button for a short time though.
