### ISSUE TITLE
Some cost quantities not working

### ISSUE THREAD

**Issue by pyure** [Lemonszz/delivery#2]
**delivery-1.3.0.jar**
Forge: 2768

Tinkering with the mod to review it, noticed the following:

```
// Works properly
mods.Delivery.Store.addTrade(<minecraft:apple> * 2, <thermalfoundation:coin:70> * 20);
mods.Delivery.Store.addTrade(<minecraft:apple> * 2, <minecraft:stone> * 20);

// Quantity is 1 instead of 20
mods.Delivery.Store.addTrade(<minecraft:apple> * 2, <ore:coinPlatinum> * 20);
mods.Delivery.Store.addTrade(<minecraft:apple> * 2, <ore:stone> * 20);
```

Common thread appears to be oredict.

Workaround is probably `<ore:dict>.firstItem` if necessary for now.

**Comment by Lemonszz** [comment]
This is tricky to solve on my end, but I found a workaround.

My ZenScript is a little rusty, but this works with all OreDict entries I tested **except planks**. I have no clue why planks don't work, they seem to be the only one that doesn't. (If anyone knows, lemme know)
```
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

function ore(dictName as string,size as int) as IIngredient{
    val dict = oreDict.get(dictName);
    var ing = dict.firstItem as IIngredient;
    ing = ing.amount(size);

    for item in dict.items{
        var it = item as IIngredient;
        it = it.amount(size);
        ing = ing.or(it);
    }

    return ing;
}

mods.Delivery.Store.addTrade(<minecraft:diamond> * 2, ore("plankWood", 20));
mods.Delivery.Store.addTrade(<minecraft:apple> * 2, ore("ingotIron", 20));
mods.Delivery.Store.addTrade(<minecraft:emerald> * 2, ore("fenceWood", 13));
mods.Delivery.Store.addTrade(<minecraft:sponge> * 2, ore("record", 4));
mods.Delivery.Store.addTrade(<minecraft:compass> * 2, ore("chest", 8));
```

If someone wants to improve the script, please post it here for others to see.

**Comment by pyure** [comment]
Wild guess: the planks have meta data (which would also make logs fail fwiw, so this theory is easily testable)

Silly question (I'm not a java dev): can't you test in addTrade() if the IIngredient is oredict, and then do the same processing there?

(The workaround seems workable, I'm just curious)

TIL: Java supports variadic parameters.  I (wrongly) assumed you had a bunch of silly overloads for addTrade() till I looked at the zenmethod code.  That said, you might want to consider accepting the inputs as an array in case you ever want subsequent IIngredient parameters that are not inputs (like, uh, "use the icon for Diamond Pickaxe" or some such)

**Comment by Lemonszz** [comment]
Yeah it does look like a meta data issue.

The problem is that both forge & crafttweaker have their Ore Dict ingredient implementations alwys returning 1 for their size. So if I process it within my code, there's no way for me to get the size specified in the script.

I'll talk to the CraftTweaker guys and see if there's a good solution.

**Comment by Lemonszz** [comment]
I've worked out a solution for this.
It's not ideal, so I'll leave the issue open for now.

Example code:
```
mods.Delivery.Store.addTrade(<minecraft:diamond> * 2).addOre("record", 5).addItem(<minecraft:apple>);
mods.Delivery.Store.addTrade(<minecraft:diamond> * 2).addOre("plankWood", 52);
mods.Delivery.Store.addTrade(<minecraft:apple> * 10, <minecraft:stick> * 5, <minecraft:brick>).addOre("plankWood", 3).addItem(<minecraft:paper> * 2);
```

This will be avalible from V1.4.0 which should be avalible in a few days.

**Comment by pyure** [comment]
From my perspective, that's absolutely good enough sir.  Since you re-opened the ticket I don't want to forcibly close it in case it breaks your workflow.  But thanks a bunch, this is nice.
