### ISSUE TITLE
Issue with method parameter

### ISSUE THREAD

**Issue by brisingraerowing** [Lemonszz/delivery#6]
---
**Mod Version**:  1.4.0

**Forge Version**: N/A (code issue)

**This issue occurs on the lastest version of Forge? (Y/N)**: N/A

**Crash Log (Post to Pastebin/Other Text hosting)**:  N/A

**What happens**:

This is an issue with the code. [This method](https://github.com/Lemonszz/delivery/blob/master/src/main/java/party/lemons/delivery/store/Trade.java#L52) has a parameter of a Minecraft Ingredient, but CT has no way of actually getting those. Instead it uses its own IIngredient interface for that. You can get the internal MC ingredient by calling getInternal on an IIngredient instance.

**Comment by Lemonszz** [comment]
Nice catch. I'll fix that up for the next release.
