### ISSUE TITLE
Store recipes messing up jei for ingots

### ISSUE THREAD

**Issue by lynaevm** [Lemonszz/delivery#8]
Please fill out this template when submitting an issue.

---
**Mod Version**:  delivery-1.12.2-1.5.1.jar

**Forge Version**:1.12.2 (modded) forge-14.23.5.2815

**This issue occurs on the lastest version of Forge? (Y/N)**: Y, just tried it on 2838 as well

**Crash Log (Post to Pastebin/Other Text hosting)**: No crash

**What happens**:

Somehow, this mod makes items in recipes in jei display improperly.  It happens for all vanilla recipes and some, but not all, modded recipes -- Botania is wrong, bibliocraft is unaffected for example.  The recipes themselves work fine.  It shows most iron ingots as requiring stacks of 2 and most gold ingots as requiring stacks of 5.  Example:

![image](https://user-images.githubusercontent.com/26103677/59162119-53b92d80-8ab1-11e9-8af5-6001f5443e79.png)

After a long morning spent doing knockout testing, I finally narrowed it down to this mod, which I have only played with a little by copying in the sample scripts.  Which happen to contain this:

![image](https://user-images.githubusercontent.com/26103677/59162132-911dbb00-8ab1-11e9-8d4d-d93c5171e6c2.png)

The numbers of iron and gold ingots align with the bizarre errors I'm getting and further investigation shows that other items are also displaying with numbers that align with their store stacks.  Deleting all the sample scripts makes the problem go away... but leaves the mod rather unusable.

**Comment by DaedalusGame** [comment]
https://github.com/Lemonszz/delivery/blob/master/src/main/java/party/lemons/delivery/store/SizedOreIngredient.java#L47
idk if you're wondering about this issue, but you're changing stacks while in the oredict, you gotta copy the list you get from getOres before modifying the stacks

**Comment by Lemonszz** [comment]
I honestly forgot about this bug - thanks for the heads up
